add image repeat flags
fallahn/tmxlite pull request #123
Opened 2023-04-14 22:12 UTC by mx-payn

Added the image repeat flags for x and y axis to ImageLayer.  

This was introduced with Tiled 1.8
[reference: tmx-changelog](https://doc.mapeditor.org/en/stable/reference/tmx-changelog/#tiled-1-8)
[reference: tmx-map-format](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#imagelayer)

2023-04-14 23:32 UTC, fallahn requested changes
Thanks! Looks like the new members are missing from the initialiser list in the constructor though?

2023-04-15 06:17 UTC, mx-payn commented
Added the missing initializers. Didn't think they would be needed ;)

2023-04-15 09:41 UTC, fallahn approved these changes

2023-04-15 09:42 UTC, fallahn commented
*Technically* not needed - but clang was complaining 😅 Thanks for the contribution!

2023-04-15 09:43 UTC, merged